
containerImage:
  repository: cocopopo/cibc_httpd
  tag: v3
  # repository: nginxinc/nginx-unprivileged
  # tag: "1"
  pullPolicy: IfNotPresent
replicaCount: 1
containerPorts: 
  http:
    port: 80
    protocol: TCP

containerCommand: 
  - sh
  - -c
  # - sleep 1h


podSecurityContext:
  fsGroup: 1000050001
  runAsUser: 1000050001
  runAsGroup: 1000050001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


securityContext: 
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL



    
canary:
  enabled: false
  replicaCount: 1
  containerImage:
    repository: cocopopo/cibc_httpd
    tag: v2
    pullPolicy: IfNotPresent


secrets: {}

configMaps: 
  cibc-demo:
    as: volume
    mountPath: /etc/myconfig
  special-config: # Configmap Name
    as: environment
    items:
      SPECIAL_LEVEL: # Value Key
        envVarName: SPECIAL_LEVEL_KEY  # Value Name

persistentVolumes: {}
scratchPaths: {}
emptyDirs: {}
initContainers: {}
imagePullSecrets: []
  # - name: regcred


deploymentStrategy:
  enabled: false
  type: RollingUpdate
  rollingUpdate: {}

applicationName: "sample"

## 추가 되는 부분
serviceMonitor:
  enabled: false

serviceAccount:
  name: ""
  create: false
  annotations: {}
  labels: {}


service:
  enabled: true
  ports:
    http:
      port: 80
      targetPort: 80
      protocol: TCP
    https:
      port: 443
      targetPort: 80
      protocol: TCP

ingress:
  enabled: true
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  path: "/"
  pathType: Prefix
  servicePort: http
  hosts:
    - nginx.sshbank.com
  tls:
    - secretName: sshbank-ca
      hosts:
        - nginx.sshbank.com


horizontalPodAutoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 10


# google:
#   managedCertificate:
#     enabled: false


lifecycleHooks:
  enabled: true

customResources:
  enabled: true
  resources:
  #### 
    custom_configmap_1: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cibc-demo
      data:
        # file-like keys
        game.properties: |
          enemy.types=aliens,monsters
          player.maximum-lives=5  
        user-interface.properties: |
          color.good=purple
          color.bad=yellow
          allow.textmode=true   
    custom_configmap_2: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: special-config
        namespace: default
      data:
        SPECIAL_LEVEL: very
        SPECIAL_TYPE: charm